### ISSUE TITLE
Proper way to use defaultCallback

### ISSUE THREAD

**Issue by gratus-acuitymd** [googleapis/nodejs-logging-bunyan#687] opened 2023-03-20 17:25 UTC
I am trying to use `defaultCallback` to capture an error so that the async write error doesn't crash the app.

Following the example, I provided a `defaultCallback` in the options like so:
```
        defaultCallback: (err, apiResponse) => {
                if (err) {
                    console.log("Error is: " + err);
                }
                else {
                    console.log("No error, all is good!");
                }
            }
```
After logging the error (`Error is:...`) the app still crashes. The specific test I am doing is to send a log entry that is too big (~350k) and the app crashes with this error:
`Uncaught Error Error: 3 INVALID_ARGUMENT: Log entry with size 347.9K exceeds maximum size of 256.0K`

I am trying to catch this error so that a) the app doesn't crash, and b) we can use the information to fix our logging.

**Comment by yelworc** [comment] 2023-04-27 08:15
Was wondering about the same thing. The process is crashing because Bunyan (I think) is emitting `error` events on the stream object, so I worked around it like this for the time being:

```javascript
const client = new LoggingBunyan();
const { level, type, stream } = client.stream();
stream.on('error', (err) => console.log(err));
bunyanCfg = {
  // …
  streams: [{ level, type, stream }],
  // …
};
```

**Comment by cindy-peng** [comment] 2023-11-28 01:05
Hi @gratus-acuitymd , by default Bunyan logger instance will reemit errors for cloud logging stream: https://github.com/trentm/node-bunyan#stream-errors.  Like suggested above, you can add a `.on()` function on the stream for error handling.

**Comment by cindy-peng** [comment] 2023-12-11 18:37
Closing this issue as this is an expected behavior from Bunyan library and a  customized`.on()` function on the stream can be added for error handling here. At this moment, adding customized listener for Bunyan client is not a team priority as there are many other prioritized work items. We will come back to this if this becomes high prioritized for the team in the future.

**Closed by cindy-peng** 2023-12-11 18:37 UTC
Labels: type: question, priority: p3, api: logging
