### ISSUE TITLE
Error Reporting does not work when `redirectToStdout` is set

### ISSUE THREAD

**Issue by tkgreg** [googleapis/nodejs-logging-bunyan#684] opened 2023-02-20 23:50 UTC
My app is running in GKE. Instead of using approach with Logging API I decided to use the simple `redirectToStdout` with `serviceContext` config. Unfortunately, it didn't work out. When I call logger.error it doesn't report to Error Reporting. Any suggestions how to solve it?

**Comment by tkgreg** [comment] 2023-02-21 11:24
I've checked again and it looks like it works only if I pass `new Error` instance to `logger.error(...)`. If I'll pass a string it does not trigger Error Reporting API. Is it expected behaviour by design or a bug?

**Comment by losalex** [comment] 2023-02-21 17:39
@tkgreg, [here](https://cloud.google.com/error-reporting/docs/formatting-error-messages) described how to format error in logs, but I believe you might not be able to set `@type` field, thus adding `new Error` is probably the way for now. More related info can be found [754](https://github.com/googleapis/nodejs-logging-winston/issues/754). Turning this issue into feature request for future tracking.

**Comment by losalex** [comment] 2023-06-27 23:04
Closing this one as a duplicate of [754](https://github.com/googleapis/nodejs-logging-winston/issues/754).

**Closed by losalex** 2023-06-27 23:04 UTC
Labels: priority: p3, type: feature request, api: logging
